PNPM=pnpm

.PHONY: dev lint typecheck test build start e2e storybook

dev:
$(PNPM) dev

lint:
$(PNPM) lint

typecheck:
$(PNPM) typecheck

test:
$(PNPM) test

e2e:
$(PNPM) e2e

build:
$(PNPM) build

start:
$(PNPM) start

storybook:
$(PNPM) storybook
