import { Router } from 'express';
import fs from 'fs';
import { v4 as uuid } from 'uuid';
const r = Router(); const FILE='data/ar/invoices.jsonl';
const append=(row:any)=>{ fs.mkdirSync('data/ar',{recursive:true}); fs.appendFileSync(FILE, JSON.stringify(row)+'\n'); };
const list=()=> fs.existsSync(FILE)?fs.readFileSync(FILE,'utf-8').trim().split('\n').filter(Boolean).map(l=>JSON.parse(l)):[];
r.post('/invoice/create',(req,res)=>{ const id=req.body?.invoiceId||uuid(); append({ invoiceId:id, ts:Date.now(), state:'issued', ...req.body }); res.json({ ok:true, invoiceId:id }); });
r.post('/invoice/state',(req,res)=>{ const rows=list().map((x:any)=> x.invoiceId===req.body?.invoiceId?{...x,state:req.body?.state||x.state}:x); fs.writeFileSync(FILE, rows.map(x=>JSON.stringify(x)).join('\n')+'\n'); res.json({ ok:true }); });
r.get('/invoice/:invoiceId',(req,res)=>{ const it=list().find((x:any)=>x.invoiceId===String(req.params.invoiceId)); if(!it) return res.status(404).json({error:'not_found'}); res.json(it); });
export default r;
