import { Router } from 'express';
import fs from 'fs';
const r = Router(); const R='treasury/fx_rates.json', D='data/treasury/fx_deals.jsonl';
const rread=()=> fs.existsSync(R)? JSON.parse(fs.readFileSync(R,'utf-8')):{ rates:{} };
const rwrite=(o:any)=>{ fs.mkdirSync('treasury',{recursive:true}); fs.writeFileSync(R, JSON.stringify(o,null,2)); };
const append=(row:any)=>{ fs.mkdirSync('data/treasury',{recursive:true}); fs.appendFileSync(D, JSON.stringify(row)+'\n'); };
const list=()=> fs.existsSync(D)? fs.readFileSync(D,'utf-8').trim().split('\n').filter(Boolean).map(l=>JSON.parse(l)):[];
r.post('/fx/rates/upsert',(req,res)=>{ const o=rread(); const { date, pairs }=req.body||{}; o.rates[date]=pairs||{}; rwrite(o); res.json({ ok:true }); });
r.post('/fx/deals/book',(req,res)=>{ append({ ts:Date.now(), ...req.body }); res.json({ ok:true }); });
r.get('/fx/recent',(_req,res)=>{ res.json({ rates: rread().rates||{}, deals: list().reverse().slice(0,200) }); });
export default r;
