PNPM?=pnpm

install:
	$(PNPM) install

dev:
	$(PNPM) dev

test:
	$(PNPM) test

lint:
	$(PNPM) lint

build:
	$(PNPM) tauri build

storybook:
	$(PNPM) storybook
.PHONY: install dev lint test storybook storybook-build tauri-build

install:
	pnpm install

dev:
	pnpm dev

lint:
	pnpm lint

test:
	pnpm test

storybook:
	pnpm storybook

storybook-build:
	pnpm build-storybook

tauri-build:
	pnpm tauri build
