export const NAMES: string[] = [
  'ROBINHOOD_ETHEREUM','ROBINHOOD_BITCOIN','ROBINHOOD_LITECOIN','ROBINHOOD_AVALANCHE','ROBINHOOD_CHAINLINK','ROBINHOOD_SOLANA','ROBINHOOD_DOGE',
  'COINBASE_BITCOIN','COINBASE_LITECOIN','COINBASE_ETHEREUM','COINBASE_NEAR','COINBASE_ATOM','COINBASE_MLN','COINBASE_GRT','COINBASE_VECHAIN','COINBASE_POLYGON',
  'VENMO_BITCOIN','VENMO_ETHEREUM','VENMO_CHAINLINK','VENMO_PAYPALUSD',
  'ETH_ADDRESS','USDT_ETH_ADDRESS','USDC_ETH_ADDRESS','BNB_BSC_ADDRESS','MATIC_POLYGON_ADDRESS','AVAX_C_ADDRESS','LINK_ETH_ADDRESS',
  'BTC_ADDRESS','LTC_ADDRESS','DOGE_ADDRESS','BCH_ADDRESS',
  'SOL_ADDRESS','TON_ADDRESS',
  'ATOM_ADDRESS','DOT_ADDRESS','XRP_ADDRESS','TRX_ADDRESS','ADA_ADDRESS'
];

export default NAMES;
