import { Router } from 'express';
import fs from 'fs';
const r = Router(); const CRQ='data/change/crq.jsonl';
const append=(row:any)=>{ fs.mkdirSync('data/change',{recursive:true}); fs.appendFileSync(CRQ, JSON.stringify(row)+'\n'); };
const list=()=> fs.existsSync(CRQ)? fs.readFileSync(CRQ,'utf-8').trim().split('\n').filter(Boolean).map(l=>JSON.parse(l)):[ ];
r.post('/crq/create',(req,res)=>{ append({ ts:Date.now(), state:'draft', approvals:[], ...req.body }); res.json({ ok:true }); });
r.post('/crq/approve',(req,res)=>{ const rows=list().map((x:any)=> x.changeId===req.body?.changeId?{...x, approvals:[...(x.approvals||[]), {approver:req.body?.approver,role:req.body?.role,ts:Date.now()}]}:x); fs.writeFileSync(CRQ, rows.map(x=>JSON.stringify(x)).join('\n')+'\n'); res.json({ ok:true }); });
r.post('/crq/state',(req,res)=>{ const rows=list().map((x:any)=> x.changeId===req.body?.changeId?{...x, state:req.body?.state}:x); fs.writeFileSync(CRQ, rows.map(x=>JSON.stringify(x)).join('\n')+'\n'); res.json({ ok:true }); });
r.get('/crq/:changeId',(req,res)=>{ const it=list().find((x:any)=>x.changeId===String(req.params.changeId)); if(!it) return res.status(404).json({error:'not_found'}); res.json(it); });
export default r;
