#!/usr/bin/env bash
set -euo pipefail

OWNER="${OWNER:-BlackRoad}"
REPO="${REPO:-masterpack}"
BASE="${BASE:-main}"
TITLE="${TITLE:-chore: bootstrap infra & flows (autogen)}"
LABELS="${LABELS:-automation,infra,flows}"
REVIEWERS="${REVIEWERS:-platform-team}"
GH_TOKEN="${GH_TOKEN:?set GH_TOKEN with repo+workflow scopes}"

BR="chore/infra-autogen-$(date +%Y%m%d-%H%M)"

echo "▶️  Creating branch $BR"
git checkout -b "$BR"

# Hook in your generator here (BLACKROAD_CODEX output sync)
if [[ -x ./scripts/sync_artifacts.sh ]]; then ./scripts/sync_artifacts.sh; fi

# Evidence bundle stub
TS=$(date -u +%Y-%m-%dT%H-%MZ)
EVDIR="evidence/${TS}_bootstrap"
mkdir -p "$EVDIR/samples"
echo "Auto generated by Athena kit" > "$EVDIR/plan.txt"
(git diff --staged || true) > "$EVDIR/diff.json" || true

# Stage + commit
git add -A
if ! git commit -m "chore: add infra/flows/monitors + runbooks [autogen]"; then
  echo "ℹ️  No changes to commit; continuing"
fi

echo "▶️  Pushing branch"
git push -u origin "$BR"

# Open PR
BODY=$'See evidence bundle under /evidence.\n\nGenerated by BLACKROAD_CODEX (Athena).\n— SLOs: P95<60s, uptime 99.9%\n— Change Mgmt: CAB packet attached\n— Ring: canary→pilot→broad'

PR=$(curl -s -X POST \
  -H "Authorization: Bearer $GH_TOKEN" \
  -H "Accept: application/vnd.github+json" \
  "https://api.github.com/repos/$OWNER/$REPO/pulls" \
  -d "{\"title\":\"$TITLE\",\"head\":\"$BR\",\"base\":\"$BASE\",\"body\":\"${BODY//$'\n'/\\n}\",\"draft\":false}")

echo "$PR" | jq . > "$EVDIR/pull_request.json"
PR_NUMBER=$(echo "$PR" | jq -r '.number')
NODE_ID=$(echo "$PR" | jq -r '.node_id')

echo "▶️  Labeling & requesting review"
curl -s -X POST -H "Authorization: Bearer $GH_TOKEN" -H "Accept: application/vnd.github+json" \
  "https://api.github.com/repos/$OWNER/$REPO/issues/$PR_NUMBER/labels" \
  -d "{\"labels\":[\"automation\",\"infra\",\"flows\"]}" >/dev/null

curl -s -X POST -H "Authorization: Bearer $GH_TOKEN" -H "Accept: application/vnd.github+json" \
  "https://api.github.com/repos/$OWNER/$REPO/pulls/$PR_NUMBER/requested_reviewers" \
  -d "{\"reviewers\":[\"$REVIEWERS\"]}" >/dev/null

# Optional: enable auto-merge (requires repo setting Allow auto-merge)
if [[ "${AUTO_MERGE:-true}" == "true" ]]; then
  curl -s -H "Authorization: Bearer $GH_TOKEN" -H "Content-Type: application/json" \
    -d '{ "query": "mutation($pr:ID!){ enablePullRequestAutoMerge(input:{pullRequestId:$pr, mergeMethod:SQUASH}){ clientMutationId }}", "variables": { "pr": "'"$NODE_ID"'" } }' \
    https://api.github.com/graphql >/dev/null || true
fi

echo "✅ PR created: https://github.com/$OWNER/$REPO/pull/$PR_NUMBER"
