#!/usr/bin/env bash
. "$(dirname "$0")/_/husky.sh" 2>/dev/null || true
if command -v commitlint >/dev/null 2>&1; then
  npx commitlint --edit "$1"
else
  echo "commitlint not installed, skipping check"
fi
